#!/bin/bash

# This program is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public
# License along with this program.  If not, see
# <https://www.gnu.org/licenses/>.
#
# Copyright (c) 2021 Zoë Sparks <zoe@milky.flowers>

md_f='vulkan_notes.md'
header_f='header.html'
body_f='body.html'
footer_f='footer.html'
html_f='vknotes.html'

build="markdown -f fencedcode -o $body_f $md_f && cat $header_f $body_f $footer_f > $html_f"
eval "$build"
gvim "$md_f"
firefox "$html_f" &
do_on_save "$md_f" "$build"
